;*****************************************************************;
;   Lanbon L10                                                    ;
;   PCB: L10_HS_CB_V1.7                                           ;
;   MCU: ESP32-S3-WROOM-1U                                        ;
;   Display : GC9503V 480x854 RGB SPI3Wire with TCA9554 expander  ;
;   Touch   : FT5x06/FT6x36 @0x38 (I2C)                           ;
;*****************************************************************;

[env:lanbon_l10]
; Reuse the common ESP32-S3 Arduino v2 base (brings in
; HASP_TARGET_ARDUINO, ArduinoJson, common libs, etc.)
extends = arduino_esp32s3_v2, flash_16mb
board = esp32-s3-devkitc-1

; Mandatory for Lanbon L10 8MB Octal PSRAM
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_flags =
    ${env.build_flags}
    ${arduino_esp32s3_v2.build_flags}
    ${esp32s3.ps_ram}
    -D HASP_USE_ARDUINOGFX=1
    -D USE_I2C_SW_SPI=1
    -D HASP_USE_EXPANDER=1
    -D GC9503V_DRIVER=1
    -D HASP_MODEL="Lanbon L10"
    -D HASP_LANBON_L10_TCA9554_GC9503V

    -D HASP_USE_CUSTOM=1
    -D USE_MOTION_WAKEUP

    ; TCA9554 Expander Pin Definitions
    -D HASP_EXPANDER_GPIO_STC_L10
    -D HASP_USE_I2C_GPIO=1
    ; Backlight on I2C virtual pin (e.g. 133): dev::Esp32_I2c_ledc extends Esp32Device
    -D HASP_ESP32_DEVICE_I2C_BACKLIGHT=1
    -D EXPANDER_MOSI=1
    -D EXPANDER_SCK=2
    -D EXPANDER_CS=3
    -D EXPANDER_RST=4
    -D EXPANDER_BL=7
    -D EXPANDER_ADDRESS=0x20
    -D EXPANDER_BACKLIGHT_CHANNEL=133
    -D EXPANDER_I2C_SDA=8
    -D EXPANDER_I2C_SCL=18
    -D EXPANDER_DRIVER=TCA9554

    ; RGB Pin Definitions
    -D TFT_WIDTH=480
    -D TFT_HEIGHT=854
    -D TFT_DE=0
    -D TFT_VSYNC=3
    -D TFT_HSYNC=46
    -D TFT_PCLK=9 ; ?? check this DCLK ..?
    -D TFT_R0=45
    -D TFT_R1=48
    -D TFT_R2=47
    -D TFT_R3=21
    -D TFT_R4=14
    -D TFT_G0=13
    -D TFT_G1=12
    -D TFT_G2=11
    -D TFT_G3=10
    -D TFT_G4=38
    -D TFT_G5=39
    -D TFT_B0=40
    -D TFT_B1=41
    -D TFT_B2=42
    -D TFT_B3=2
    -D TFT_B4=1
    -D TFT_RST=-1

    ; RGB Timings
    -D TFT_HSYNC_POLARITY=1
    -D TFT_HSYNC_FRONT_PORCH=20
    -D TFT_HSYNC_PULSE_WIDTH=8
    -D TFT_HSYNC_BACK_PORCH=40
    -D TFT_VSYNC_POLARITY=1
    -D TFT_VSYNC_FRONT_PORCH=10
    -D TFT_VSYNC_PULSE_WIDTH=4
    -D TFT_VSYNC_BACK_PORCH=16

    ; RGB Panel tuning
    -D TFT_PCLK_ACTIVE_NEG=1
    -D TFT_PREFER_SPEED=18000000

    ; Touch Controller (FT5x06/FT6x36)
    -D TOUCH_WIDTH=480
    -D TOUCH_HEIGHT=854
    -D TOUCH_DRIVER=0x6336
    -D TOUCH_SCL=18
    -D TOUCH_SDA=8
    -D TOUCH_IRQ=-1
    -D TOUCH_RST=-1
    -D I2C_TOUCH_ADDRESS=0x38
    -D I2C_TOUCH_PORT=1
    -D I2C_TOUCH_FREQUENCY=400000


lib_deps =
    ${env.lib_deps}
    ${esp32s3.lib_deps}
    ${arduino_esp32s3_v2.lib_deps}
    ${arduinogfx.lib_deps}
    ${ft6336.lib_deps}