;**********************************************************;
;   Waveshare ESP32-S3-Touch-LCD-2 240x320 C-Touch        ;
;     - ST7789T3 TFT SPI 4-WIRE                           ;
;     - CST816D capacitive touch controller               ;
;**********************************************************;

[env:waveshare-esp32-s3-touch-lcd-2]
extends = arduino_esp32s3_v2, flash_16mb
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi

build_flags =
    -D HASP_MODEL="Waveshare ESP32-S3-Touch-LCD-2"
    ${arduino_esp32s3_v2.build_flags}
    ${esp32s3.ps_ram}

    ; Native USB console
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USE_USB_CDC_CONSOLE=1

    ; Display
    -D LGFX_USE_V1=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_ROTATION=0
    -D TFT_MOSI=38
    -D TFT_MISO=40
    -D TFT_SCLK=39
    -D TFT_CS=45
    -D TFT_DC=42
    -D TFT_RST=-1
    -D TFT_BCKL=1
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=80000000

    ; Touch
    -D TOUCH_DRIVER=0x816
    -D HASP_USE_LGFX_TOUCH=1
    -D TOUCH_SDA=48
    -D TOUCH_SCL=47
    -D TOUCH_IRQ=-1
    -D TOUCH_RST=-1
    -D I2C_TOUCH_PORT=0
    -D I2C_TOUCH_ADDRESS=0x15
    -D I2C_TOUCH_FREQUENCY=400000
    -D TOUCH_OFFSET_ROTATION=0

lib_deps =
    ${arduino_esp32s3_v2.lib_deps}
    ${lovyangfx.lib_deps}

upload_protocol = esp-builtin
