.section .rodata.embedded, "a"
.align 4

.global _binary_data_static_edit_htm_gz_start
.global _binary_data_static_edit_htm_gz_end

.type _binary_data_static_edit_htm_gz_start, @object
.type _binary_data_static_edit_htm_gz_end, @object

_binary_data_static_edit_htm_gz_start:
    .incbin "data/static/edit.htm.gz"

_binary_data_static_edit_htm_gz_end:

.size _binary_data_static_edit_htm_gz_start, .-_binary_data_static_edit_htm_gz_start


.align 4

.global _binary_data_static_style_css_gz_start
.global _binary_data_static_style_css_gz_end

.type _binary_data_static_style_css_gz_start, @object
.type _binary_data_static_style_css_gz_end, @object

_binary_data_static_style_css_gz_start:
    .incbin "data/static/style.css.gz"

_binary_data_static_style_css_gz_end:

.size _binary_data_static_style_css_gz_start, .-_binary_data_static_style_css_gz_start


.align 4

.global _binary_data_static_script_js_gz_start
.global _binary_data_static_script_js_gz_end

.type _binary_data_static_script_js_gz_start, @object
.type _binary_data_static_script_js_gz_end, @object

_binary_data_static_script_js_gz_start:
    .incbin "data/static/script.js.gz"

_binary_data_static_script_js_gz_end:

.size _binary_data_static_script_js_gz_start, .-_binary_data_static_script_js_gz_start


.align 4

.global _binary_data_static_logo_svg_gz_start
.global _binary_data_static_logo_svg_gz_end

.type _binary_data_static_logo_svg_gz_start, @object
.type _binary_data_static_logo_svg_gz_end, @object

_binary_data_static_logo_svg_gz_start:
    .incbin "data/static/logo.svg.gz"

_binary_data_static_logo_svg_gz_end:
.size _binary_data_static_logo_svg_gz_start, .-_binary_data_static_logo_svg_gz_start


.align 4

.global _binary_data_static_petite_vue_hasp_js_gz_start
.global _binary_data_static_petite_vue_hasp_js_gz_end

.type _binary_data_static_petite_vue_hasp_js_gz_start, @object
.type _binary_data_static_petite_vue_hasp_js_gz_end, @object

_binary_data_static_petite_vue_hasp_js_gz_start:
    .incbin "data/static/petite-vue.hasp.js.gz"

_binary_data_static_petite_vue_hasp_js_gz_end:

.size _binary_data_static_petite_vue_hasp_js_gz_start, .-_binary_data_static_petite_vue_hasp_js_gz_start


.align 4

.global _binary_data_static_main_js_gz_start
.global _binary_data_static_main_js_gz_end

.type _binary_data_static_main_js_gz_start, @object
.type _binary_data_static_main_js_gz_end, @object

_binary_data_static_main_js_gz_start:
    .incbin "data/static/main.js.gz"

_binary_data_static_main_js_gz_end:

.size _binary_data_static_main_js_gz_start, .-_binary_data_static_main_js_gz_start


.align 4

.global _binary_data_static_en_json_gz_start
.global _binary_data_static_en_json_gz_end

.type _binary_data_static_en_json_gz_start, @object
.type _binary_data_static_en_json_gz_end, @object

_binary_data_static_en_json_gz_start:
    .incbin "data/static/en.json.gz"

_binary_data_static_en_json_gz_end:

.size _binary_data_static_en_json_gz_start, .-_binary_data_static_en_json_gz_start


.align 4

.global _binary_data_openhasp_ttf_start
.global _binary_data_openhasp_ttf_end

.type _binary_data_openhasp_ttf_start, @object
.type _binary_data_openhasp_ttf_end, @object

_binary_data_openhasp_ttf_start:
    .incbin "data/openhasp.ttf"

_binary_data_openhasp_ttf_end:

.size _binary_data_openhasp_ttf_start, .-_binary_data_openhasp_ttf_start


.align 4

.global _binary_data_pages_pages_jsonl_start
.global _binary_data_pages_pages_jsonl_end

.type _binary_data_pages_pages_jsonl_start, @object
.type _binary_data_pages_pages_jsonl_end, @object

_binary_data_pages_pages_jsonl_start:
    .incbin "data/pages/pages.jsonl"

_binary_data_pages_pages_jsonl_end:

.size _binary_data_pages_pages_jsonl_start, .-_binary_data_pages_pages_jsonl_start


.align 4

.global _binary_data_cert_x509_crt_bundle_bin_start
.global _binary_data_cert_x509_crt_bundle_bin_end

.type _binary_data_cert_x509_crt_bundle_bin_start, @object
.type _binary_data_cert_x509_crt_bundle_bin_end, @object

_binary_data_cert_x509_crt_bundle_bin_start:
    .incbin "data/cert/x509_crt_bundle.bin"

_binary_data_cert_x509_crt_bundle_bin_end:

.size _binary_data_cert_x509_crt_bundle_bin_start, .-_binary_data_cert_x509_crt_bundle_bin_start





