[env:m5stack_core2_new]
extends = arduino_esp32_v3, flash_16mb
board = esp32dev

# Define custom BSP dependencies directly here
custom_bsp_dependencies =
     espressif/m5stack_core_2: "^1.0.0"
     lvgl/lvgl: "^7.11.0"
     espressif/esp_lvgl_port: "^1.0.0"

build_flags =
    -D HASP_MODEL="M5Stack Core2"
    -D BSP_CONFIG_NO_GRAPHIC_LIB=1
    -D LV_CONF_INCLUDE_SIMPLE
    -I src/
    ${arduino_esp32_v3.build_flags}
    ${esp32.ps_ram}
build_unflags = 
    -D CONFIG_LOG_DEFAULT_LEVEL=3       ; Silences standard Espressif framework output strings
    -D CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL=2  ; Silences all framework assert strings
    -D CONFIG_ESP_ERR_TO_NAME_LOOKUP=1  ; Removes large internal error-code-to-string lookup tables
    -Wno-incompatible-pointer-types